const USERNAME_LENGTH = 20
const USER_AVATAR_LENGTH = 100
const USER_PET_LENGTH = 40
const USER_CAREER_LENGTH = 20
const USER_SCHOOL_LENGTH = 40
const USER_SKILL_LENGTH = 40
const USER_PROFILE_LENGTH = 250
const COLLECTION_NAME_LENGTH = 50
const REMARK_CONTENT_LENGTH = 50
const REVIEW_CONTENT_LENGTH = 100

module.exports = {
  USERNAME_LENGTH,
  USER_AVATAR_LENGTH,
  USER_PET_LENGTH,
  USER_CAREER_LENGTH,
  USER_SCHOOL_LENGTH,
  USER_SKILL_LENGTH,
  USER_PROFILE_LENGTH,
  COLLECTION_NAME_LENGTH,
  REMARK_CONTENT_LENGTH,
  REVIEW_CONTENT_LENGTH
}
