const USER_AVATAR_LENGTH = 100
const USER_PET_LENGTH = 40
const USER_CAREER_LENGTH = 20
const USER_SCHOOL_LENGTH = 40
const USER_SKILL_LENGTH = 40
const USER_PROFILE_LENGTH = 250
module.exports = {
  USER_AVATAR_LENGTH,
  USER_PET_LENGTH,
  USER_CAREER_LENGTH,
  USER_SCHOOL_LENGTH,
  USER_SKILL_LENGTH,
  USER_PROFILE_LENGTH
}
